export const mockEvents = [
  {
    event_id: 1,
    neighbor: 1,
    event_description: "mock event description",
    event_name: "mock event name",
    event_start_date: "",
    event_end_date: "",
    event_reoccur: "",
    event_address: "",
    event_city: "",
    event_state: "",
    event_zipcode: "",
    event_public: true,
    event_private: false,
    event_invitees: "",
    event_when: "",
    neighborhood: 1,
  },
  {
    event_id: 2,
    neighbor: 2,
    event_description: "mock event description2",
    event_name: "mock event name2",
    event_start_date: "",
    event_end_date: "",
    event_reoccur: "",
    event_address: "",
    event_city: "",
    event_state: "",
    event_zipcode: "",
    event_public: true,
    event_private: false,
    event_invitees: "",
    event_when: "",
    neighborhood: 1,
  },
  {
    event_id: 3,
    neighbor: 3,
    event_description: "mock event description3",
    event_name: "mock event name3",
    event_start_date: "",
    event_end_date: "",
    event_reoccur: "",
    event_address: "",
    event_city: "",
    event_state: "",
    event_zipcode: "",
    event_public: true,
    event_private: false,
    event_invitees: "",
    event_when: "",
    neighborhood: 1,
  },
  {
    event_id: 4,
    neighbor: 4,
    event_description: "mock event description4",
    event_name: "mock event name4",
    event_start_date: "",
    event_end_date: "",
    event_reoccur: "",
    event_address: "",
    event_city: "",
    event_state: "",
    event_zipcode: "",
    event_public: true,
    event_private: false,
    event_invitees: "",
    event_when: "",
    neighborhood: 1,
  },
];
